### ISSUE TITLE
Metadata.java line 161

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#1271]
#### in com.enaixpeend.metadata.Metadata$SavePhotoTask.doInBackground

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b967eb46007d59fcd3f206f?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b967eb46007d59fcd3f206f?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
`

Caused by java.lang.NullPointerExceptionAttempt to get length of null array Raw Text
--
  | java.io.FileOutputStream.write (FileOutputStream.java:296)
  | com.enaixpeend.metadata.Metadata$SavePhotoTask.doInBackground (Metadata.java:161)
  | com.enaixpeend.metadata.Metadata$SavePhotoTask.doInBackground (Metadata.java:147)
  | android.os.AsyncTask$2.call (AsyncTask.java:305)
  | java.lang.Thread.run (Thread.java:760)

`
