### ISSUE TITLE
NativeConverter.java

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#240]
#### in libcore.icu.NativeConverter.closeConverter

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7838f76007d59fcd26e3b4?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7838f76007d59fcd26e3b4?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
This is an Android system-level crash that happened because JVM garbage collection took too long. It was likely caused by an incorrect clean-up of native resources, or because garbage collection occurred while your app was backgrounded. Although this crash cannot be avoided, you can mitigate its effects. For more details, check out the first resource.
